spring:
  profiles:
    active: dev
  application:
    name: API Catalog for List Prices
  r2dbc:
    url: r2dbc:h2:mem://localhost/~/testdb
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
application:
  scheduler:
    period-milliseconds: 60000
  csv:
#    Cambiar ruta .csv
    path: /home/leonard/Documentos/Proyectos/zara-catalog/src/main/resources/prices.csv


server:
  port: 9090